
export const FETCH_WEATHER_START = 'weather/FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'weather/FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'weather/FETCH_WEATHER_FAIL';
